version: '3.4'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
    restart: on-failure
    ports:
      - "9200:9200"
    volumes:
      - ./target/releases/elasticsearch-analysis-khmerlang-${ES_VERSION}.zip:/usr/share/elasticsearch/plugin/elasticsearch-analysis-khmerlang-${ES_VERSION}.zip
      - ./install-es-plugin.sh:/apps/install-es-plugin.sh
    environment:
      - "ES_VERSION=${ES_VERSION}"
      - "ELASTIC_PASSWORD=${ELASTIC_PASSWORD}"
      - "discovery.type=single-node"
    entrypoint:
      - /apps/install-es-plugin.sh
  kibana_khmerlang:
    image: docker.elastic.co/kibana/kibana:${ES_VERSION}
    container_name: kibana_khmerlang
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    depends_on:
      - elasticsearch
